server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tC4ZWAmycPjz8k6NxR7
    keySecret: gncKuOV6OqXsjNj00waZHuBb3rzwcB
    bucketName: zhanghui-file